import math

TICK_ENABLED = True

MARGIN_BOTTOM_TOP = 30
MARGIN_LEFT_RIGHT = 30

PIXELS_PER_UNIT = 30
SHAPESIZE = PIXELS_PER_UNIT * (1 / 20)

NUM_TILES_COL = 10
NUM_TILES_ROW = 20

TICK_STEP = math.floor((1 / 60) * 1000)

SCREENWIDTH = NUM_TILES_COL * PIXELS_PER_UNIT + MARGIN_BOTTOM_TOP * 2
SCREENHEIGHT = NUM_TILES_ROW * PIXELS_PER_UNIT + MARGIN_LEFT_RIGHT * 2
